title: "Danial Amin-Portfolio"
author: "Danial Amin"
description: "Data Scientist with 05 years of hands-on experience in Engineering Data
        , Google Certified, IBM Certified, AWS Certified" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "writetodanialamin@mail.com"
twitter_username: "dany_amin"
github_username: "danial-amin"
linkedin_username: "danialamin"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss
kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
